version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
    command:
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.myresolver.acme.httpchallenge=true
      - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.myresolver.acme.email=icaro.wsilva@al.infnet.edu.br
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
      - --log.level=DEBUG
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_certs:/letsencrypt
    networks:
      - app_network

  laravel_migrate:
    image: mob2you/devops-skate-events:latest
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none
      placement:
        constraints: [ node.role == manager ]
    command: >
      sh -c "php -r '
        \$retries = 0;
        while (\$retries < 30) {
          try {
            \$db = new PDO(
              \"mysql:host=$$DB_HOST;port=$$DB_PORT;dbname=$$DB_DATABASE\",
              \"$$DB_USERNAME\",
              \"$$DB_PASSWORD\",
              [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION, PDO::ATTR_TIMEOUT => 5]
            );
            \$db = null;
            break;
          } catch (PDOException \$e) {
            \$retries++;
            sleep(2);
          }
        }
        if (\$retries >= 30) exit(1);
      ' && php artisan migrate --force"
    environment:
      APP_ENV: local
      DB_CONNECTION: mysql
      DB_HOST: 192.168.68.105
      DB_PORT: 3306
      DB_DATABASE: devops_skate_events
      DB_USERNAME: sail
      DB_PASSWORD: password
    networks:
      - app_network

  laravel_app:
    image: mob2you/devops-skate-events:latest
    deploy:
      replicas: 3
      labels:
        - traefik.enable=true
        - traefik.http.routers.laravel_app.rule=Host(`sandbox.gestordevalores.com.br`)
        - traefik.http.services.laravel_app.loadbalancer.server.port=80
        - traefik.http.routers.laravel_app.entrypoints=websecure
        - traefik.http.routers.laravel_app.tls.certresolver=myresolver
    environment:
      APP_ENV: local
      APP_PORT: 8000
      APP_URL: https://0.0.0.0:8000
      DB_CONNECTION: mysql
      DB_HOST: 192.168.68.105
      DB_PORT: 3306
      DB_DATABASE: devops_skate_events
      DB_USERNAME: sail
      DB_PASSWORD: password
    networks:
      - app_network

networks:
  app_network:
    driver: overlay

volumes:
  traefik_certs:
    driver: local
